server:
  token: 123456
  port: 3384
  websocketPort: 9000

web:
  enable: true
  title: Zolo's Server Monitor

notifier:
  telegram:
    enable: true
    # useEmbed: Use the built-in Bot for this application. If you are in mainland China, enabling this option will cause you to be unable to send and receive notifications due to network failure.
    useEmbed: false
    language: chinese
    botToken: xxxxxxxxxxxxxxxxxxxxxxxxxxx
    userId: 1953745499
