server:
  token: 123456
  port: 3384
  websocketPort: 9000

web:
  enable: true
  title: Zolo's Server Monitor

notifier:
  telegram:
    enable: false
    botToken: 5185378646:AAH8tODlas2eq-WwAVHc5_g3_mh6jDCd-o0